### ISSUE TITLE
how to get the eigenvector and eigenvalue?

### ISSUE THREAD

**Issue by silvewheat** [Rosemeis/pcangsd#1]
Hello,
        I apply pcangsd in genotype likelihoods in Beagle format (from angsd), and get the results with suffix include .cov  .inbreed .indmafs.gz .mafs.gz .selection.gz.  But I can not find the result of PC in each individual. I hope to draw a picture like this.
![image](https://user-images.githubusercontent.com/19344997/30916857-fcf6feea-a3cc-11e7-8c93-b4bd63ad963c.png)
       In the .selection.gz file I see something like that, but each row is snp, not individual.
![image](https://user-images.githubusercontent.com/19344997/30916959-54384326-a3cd-11e7-8e13-a408d926d215.png)
       How I can get a picture like the normal pca show?

Thank you!

**Comment by Rosemeis** [comment]
PCAngsd has now been fully updated. You can obtain the principal components by performing an eigendecomposition of the covariance matrix (.cov). This is either done in R with "eigen(C)" or in Python using the Numpy library with "numpy.linalg.eig(C)".
