### ISSUE TITLE
diagonal of kinship matrix

### ISSUE THREAD

**Issue by ovidp** [Rosemeis/pcangsd#11]
The kinship matrix (obtained with -inbreed 3 option) does not have 1s on the diagonal. Acually the values obtained on the diagonal in my data are between 0.13 and 0.55. Can you please shortly explain what these represent? Congratulations for a very nice software! It is highly useful.

**Comment by Rosemeis** [comment]
I will close this issue. Please feel free to re-open if needed. :-)
