### ISSUE TITLE
Error pcangsd.py cannot copy sequence to array

### ISSUE THREAD

**Issue by jdaron** [Rosemeis/pcangsd#12]
Hi everyone,

I have been getting a weird error with pcangsd.py.

Here is the report of the error.

Traceback (most recent call last):
  File "/work/jdaron/bin/pcangsd/pcangsd.py", line 138, in <module>
    likeMatrix = readGzipBeagle(args.beagle, args.allocate_sites)
  File "/work/jdaron/bin/pcangsd/helpFunctions.py", line 32, in readGzipBeagle
    likeMatrix[c, :] = line.split("\t")[3:]
ValueError: cannot copy sequence with size 29 to array axis with dimension 1392

The command line I am launching to get this error is 
python pcangsd.py -beagle angsd.PV.PL.5x.beagle.gz -o angsd.PV.PL.5x.pca -threads 10

Before than I male the beagle file launching:
angsd -P 8 -bam $bamfile -out $prefix -minQ 20 -minMapQ 30 -GL 1 -doMajorMinor 1 -doMaf 1 -doPost 2 -doGeno 32 -minMaf 0.05 -SNP_pval 2e-6 -minInd $minInd -doGlf 2 -doIBS 1 -doCounts 1 -doCov 1  -makeMatrix 1 -dohaplocall 1

I should mentionne the angsd command line with the -doCov 1 option is outputing the same error as the python pcangsd.py command line.

Weirdly I successed to run both command line and get the covariance matrice with a sub set of 10 bam files. I get this error with ~1000 bam files.

Here is the version of angsd I am using
	-> angsd version: 0.918 (htslib: 1.5) build(Jan 10 2018 09:50:37)

Thanks a lot for you help

**Comment by Rosemeis** [comment]
Hi,

This sounds like a problem that is originating in ANGSD during the generation of the genotype likelihood file. The error indicates that perhaps ANGSD was interrupted before completion as the current SNP doesn't have GL information for the 464 samples you are looking at, when inputting to PCAngsd.

I would suggest trying to run ANGSD again and see that nothing goes wrong (might be a memory issue).
Another fix could be to remove the last 2 lines of the beagle file and see if it runs now. And maybe check the chr and pos of the last few lines to see if ANGSD was interrupted. However, of course that also means that you will not analyze all variable sites in PCAngsd!

Hope this helps you a little bit.
/Jonas
