### ISSUE TITLE
-sites_save not printing correctly?

### ISSUE THREAD

**Issue by alexpiper** [Rosemeis/pcangsd#15]
Hi Jonas,

I think i have come across a bug with the -sites_save functionality. The input beagle file has site names like this (for contig 1):

```
JHQJ01000001.1_1000
JHQJ01000001.1_1002
JHQJ01000001.1_1006
JHQJ01000001.1_1008
JHQJ01000001.1_1009
JHQJ01000001.1_1010
JHQJ01000001.1_1011
JHQJ01000001.1_1012
JHQJ01000001.1_1014
JHQJ01000001.1_1015
```
Whereas the output of -sites_save looks like this:

```
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
JHQJ01000001.1_1
```
And so on and so forth. Am i right in thinking that -sites_save is only printing the first character of each site? or i am not understanding how to parse the file correctly

Im using PCAngsd 0.973

Cheers,
Alex

**Comment by Rosemeis** [comment]
Hi Alex,

You are definitely right. I had capped the size at 16 for the site-array! But I have increased it to 24 now, so it should be able to handle longer site IDs. :-)

Best,
Jonas

**Comment by alexpiper** [comment]
Perfect, that's solved it. Thanks for the quick fix!
