### ISSUE TITLE
 PCAngsd npy matrix not working in R

### ISSUE THREAD

**Issue by Giovannino1984** [Rosemeis/pcangsd#16]
Hi,

 I am trying to visualize a PCA plot after using PCAngsd 0.98 with R.3.5.3

I benefited from reading the useful pertinent post https://github.com/Rosemeis/pcangsd explaining how to make R read Numpy matrices. Nevertheless, I got stuck at the following passage, and I guess the reason is that the matrix is not properly read.

  
library(ggplot2)
library(xlsx)
library(RcppCNPy)
C <- npyLoad("/home/wildlife_genome/RISULTATIANGSD1.cov.npy")
e <- eigen(cov)
Error in as.vector(x, mode) :
   cannot coerce type 'closure' to vector of type 'any' 

I am wondering if anyone has ever faced the same problem and can provide me some feedback.
Thanks

**Comment by sandyplus** [comment]
eigen(cov)?
 SHOULD BE eigen(C)
