### ISSUE TITLE
command error during selection scan 

### ISSUE THREAD

**Issue by Callithrix-omics** [Rosemeis/pcangsd#17]
Hello, 
When I try to run a selection scan in the form of, respectively:
python pcangsd.py -beagle data.beagle.gz -selection 1 -o test -threads 10 
python pcangsd.py -beagle data.beagle.gz -selection 2 -o test -threads 10 

I get an errors, respecitively
PCAngsd: error: unrecognized arguments: 1
PCAngsd: error: unrecognized arguments: 2

When I run a selection scan as 
python pcangsd.py -beagle data.beagle.gz -selection  -o test -threads 10 

PCA runs and outputs values such as 
array([[0.27868226],
       [1.93282664],
       [0.24144043],
       ...,
       [0.76879704],
       [0.24876428],
       [2.347754  ]])

Are these values based on FASTPCA or PCAAdapt or something else?

**Comment by Rosemeis** [comment]
Hi,

Yes sorry, the wiki is not updated to follow the newest version of PCAngsd! There is only one option now, and that selection scan is based on the FastPCA selection scan (Galinsky et al.).

So each column will be the selection coefficient along that PC.

Best,
Jonas
