### ISSUE TITLE
Clarification regarding format of the covariance matrix for V0.98

### ISSUE THREAD

**Issue by albinap** [Rosemeis/pcangsd#20]
I am a bit confused re the output of PCAngsd V0.98 in the explanation you say: "Since version 0.98, PCAngsd is now outputting solely in binary Numpy format (.npy) except for the covariance matrix."

However when I ran PCAngsd on my data using this command: 
python3 /pcangsd_0.98/pcangsd/pcangsd.py -beagle $INPUT -minMaf 0.05 -o $OUTPUT

The output was: OUTPUT.cov.npy and the file looks very different from when I was using the older version.

I am consequently having issues with getting my PCA plotting to work.

P.S. Love how fast PCAngsd is now!

**Comment by Rosemeis** [comment]
Yes, I'm sorry that is typo! From v.0.981 (most recent version) the statement holds, so v.0.98 still outputs the covariance matrix in binary numpy format (.npy).

Could it be that a different number of eigenvectors were retained for the estimation of the covariance matrices? Based on your command PCAngsd will automatically infer this number, and the test for it might have slightly changed in the re-implementation. You could try and manually select a suitable number of eigenvectors to retain (-e parameter).

Best,
Jonas

**Comment by albinap** [comment]
Thank you for the clarification re the format, I am now using V0.981 and my plotting is working but one of my samples is suddenly much further away on the PCA plot than it used to be when I used the older version of PCAngsd.
Is there a way that I can see how many eigenvectors PCAangsd is using? If not how would I know what number to change it to? Or at least which values to try using? I have no idea right now.

**Comment by Rosemeis** [comment]
You would be able to see it in the output printed to screen during running PCAngsd. If you don't have that, then you would still be able to deduce it if you also ran "-selection" or "-admix". Number of eigenvectors to use is kind of similar to the K value in structure/ADMIXTURE. If you have K distinct population then you would need e = K-1 eigenvectors to represent population structure in PC-space.

In the next release of PCAngd, I will make it output a log-file such that these issues will be easier to solve. :-)

/Jonas

**Comment by albinap** [comment]
This is my screen output (and I make my own log file with |& tee -a PCAngsd_logfileminMaf_0.05.txt)
So would I go for 13?

Read 50 samples and 1025695 sites

Estimating population allele frequencies
EM (MAF) converged at iteration: 7

Number of sites after MAF filtering (0.05): 768037

Estimating covariance matrix
Using 1 principal components (MAP test)
Individual allele frequencies estimated (1)
Individual allele frequencies estimated (2). RMSE=0.014265291860136047
Individual allele frequencies estimated (3). RMSE=0.0059580647024536125
Individual allele frequencies estimated (4). RMSE=0.002866350141681356
Individual allele frequencies estimated (5). RMSE=0.0014709114776705588
Individual allele frequencies estimated (6). RMSE=0.0007812655980422219
Individual allele frequencies estimated (7). RMSE=0.0004236767750309512
Individual allele frequencies estimated (8). RMSE=0.00023313160375477605
Individual allele frequencies estimated (9). RMSE=0.00012939066704927414
Individual allele frequencies estimated (10). RMSE=7.281453599037322e-05
Individual allele frequencies estimated (11). RMSE=4.141673814312894e-05
Individual allele frequencies estimated (12). RMSE=2.3663097931484476e-05
Individual allele frequencies estimated (13). RMSE=1.3604766800426788e-05
Individual allele frequencies estimated (14). RMSE=8.240925669757597e-06
Estimation of individual allele frequencies has converged.

**Comment by Rosemeis** [comment]
Okay perfect. Sorry, I use eigenvector and principal components (PCs) interchangeably here. So in your case, you are using 1 eigenvector (PC) to capture population structure. You can override the automatic test with the "-e" parameter. You can consider to increase it, if you expect more than K=2 (e=1, e=K-1) distinct populations.

/Jonas
