### ISSUE TITLE
Segmentation fault estimating covariance matrix

### ISSUE THREAD

**Issue by cursorially** [Rosemeis/pcangsd#21]
Hi there, I get a segmentation fault when running the following code:

`./pcangsd.py -beagle test.beagle.gz -o test.output`

Full output to console is

`rsb0001634:test.angsd oliverstuart$ python $pcangsdpath -beagle test.beagle.gz -o test.an -threads 1
PCAngsd 0.981
Using 1 thread(s)

Parsing Beagle file
Segmentation fault: 11`

Running `./pcangsd.py -h` gives me the desired output. Is it likely that this a known problem relating to my installation or a file issue? I've used ATLAS (https://bitbucket.org/wegmannlab/atlas/wiki/Auxiliary%20VCF%20Tools:%20VCFToBeagle) to convert my `.vcf` to `.BEAGLE` format.

**Comment by Rosemeis** [comment]
Hi,

Yes that might be. ANGSD outputs genotype likelihoods in a tab-separated format, which PCAngsd is setup to read directly from. So perhaps ATLAS outputs genotype likelihoods in single-space separated format? If that is the case, I will make PCAngsd able to read both formats in the future!

Best,
Jonas

**Comment by cursorially** [comment]
Hi Jonas,

Thanks for your prompt reply! I don't believe that's the issue, my file ([test.beagle.gz](https://github.com/Rosemeis/pcangsd/files/3791583/test.beagle.gz)) is tab-separated.

So probably an installation issue?

Ollie

**Comment by Rosemeis** [comment]
Hi Ollie,

Had a look at your file with my own installation. I also get segmentation fault but that was due to the last line not being complete! So a simple "zcat test.beagle.gz | head -n 111 > test2.beagle; gzip test2.beagle" made the file parsable. :-)

Is it also your case for the full beagle file? Maybe ATLAS terminated pre-maturely or something similar.

/Jonas

**Comment by cursorially** [comment]
Thanks Jonas,

That was the problem. One of my variants had N as the reference which ATLAS didn't like, so it spit out the final line with nothing on it, so PCangsd threw a segfault.

Ollie

**Comment by Rosemeis** [comment]
No problem! :-)

/Jonas
