### ISSUE TITLE
specify a region on which pcangsd will run

### ISSUE THREAD

**Issue by clairemerot** [Rosemeis/pcangsd#22]
We are interested in running PCA on different parts of the genome. Until now, we have been splitting manually the beagle file based on the information LG_ position in the first column (output of angsd) but I was wondering whether maybe this is already implemented in pcangsd? 
Thank you!
Claire

**Comment by Rosemeis** [comment]
Hi Claire,
Right now it's not implemented. But I will keep it in my mind for next update.
/Jonas

**Comment by clairemerot** [comment]
Thanks a lot. No trouble for now, we are currently splitting the beagle file before running  pcangsd.
This, it is particularly useful to make PCA by chromosome, or apply methods such as local PCA, which are a useful tool for detecting substructure such as rearrangements (see lostruct methods https://doi.org/10.1101/070615).
