### ISSUE TITLE
Can linked sites influence pcangsd result?

### ISSUE THREAD

**Issue by biozzq** [Rosemeis/pcangsd#23]
Dear @Rosemeis 

When running PCA analysis based on hard genotype, we usually run prunning to remove the linked sites. Can linked sites bias the results of pcangsd?

kind regards,
Zhuqing

**Comment by Rosemeis** [comment]
Dear Zhuqing,

Yes, it can be biased as we assume sites are independent but it is usually miniscule.

Best,
Jonas

**Comment by Rosemeis** [comment]
I will close this issue. Feel free to re-open if needed. :-)
