### ISSUE TITLE
negative dimensions are not allowed

### ISSUE THREAD

**Issue by zyxplus** [Rosemeis/pcangsd#24]
I used the command line 
"python /ANGSD_PCA/tool/pcangsd/pcangsd.py -beagle unlink.new.gz -o unlink.new.gz.cov -threads 5".

I got the genotype likelihood in beagle format from gatk3.3-ProduceBeagleInput funcion

The report is as follows:
Parsing Beagle file
Traceback (most recent call last):
  File "/ANGSD_PCA/tool/pcangsd/pcangsd.py", line 133, in <module>
    L = reader.readBeagle(args.beagle).T
  File "reader.pyx", line 13, in reader.readBeagle
    cpdef readBeagle(str beagle):
  File "reader.pyx", line 32, in reader.readBeagle
    cdef np.ndarray[DTYPE_t, ndim=2, mode='fortran'] L_np = np.empty((m, n), dtype=DTYPE, order='F')
ValueError: negative dimensions are not allowed

Any suggestions please? 
Wrong input format? 
Not allow missing?

**Comment by Rosemeis** [comment]
Hi,
I suspect that it might be due to the beagle file not being tab-separated.
Please let me know if that helps. :-)

/Jonas

**Comment by zyxplus** [comment]
It works! Thanks!

**Comment by Rosemeis** [comment]
That's good to hear, I will close the issue. :-)
/Jonas
