### ISSUE TITLE
ZeroDivisionError: float division

### ISSUE THREAD

**Issue by zyxplus** [Rosemeis/pcangsd#26]
error log is as following:

Estimating population allele frequencies
Traceback (most recent call last):
  File "/mnt/disk2_workspace/angsdPCA/pcangsd/pcangsd.py", line 157, in <module>
    f = emMaf.alleleEM(L, args.maf_iter, args.maf_tole, args.threads)
  File "/mnt/disk2_workspace/angsdPCA/pcangsd/emMaf.py", line 20, in alleleEM
    shared.emMaf_update(L, f, newF, t) # Updated allele frequencies
  File "shared.pyx", line 78, in shared.emMaf_update
    cpdef emMaf_update(float[:,::1] L, float[::1] f, float[::1] newF, int t):
  File "shared.pyx", line 90, in shared.emMaf_update
    newF[j] = newF[j] + (p1 + 2*p2)/(2*(p0 + p1 + p2))
ZeroDivisionError: float division

Does it caused by missing genoype? or something else?

**Comment by Rosemeis** [comment]
Hi,

How are your genotype likelihoods encoded? If missing values are encoded as 0 then this will happen.

Best,
Jonas

**Comment by murielgrosb** [comment]
Hello,
I am having the same issue. I generated the Beagle file using ANGSD.
What is the solution? Should I change the encoding of missing values??
Thanks,
Muriel

**Comment by Rosemeis** [comment]
If you generated it through ANGSD, then it shouldn't be a problem. Did you modify the Beagle file in anyway?

**Comment by murielgrosb** [comment]
Yeah I combined multiple beagle files after generating one beagle per contig, that's probably where there is an issue then and I will check this again!
Thanks!

**Comment by cbossu** [comment]
Hello,
I know this is an older post, but this has only recently become an issue for us. My collaborators are getting the following error when running the newer version of pcangd (v1.21). We have converted an imputed vcf file (no missing data) to a bed file in plink, and we are running pcangsd --admix across multiple values of -e.  The error, attached below, shows pcangsd is reading the plink file.

Parsing PLINK files.
Loaded 1872314 sites and 121 individuals.
Estimating minor allele frequencies.
Traceback (most recent call last):
  File "/usr/local/Dist/anaconda-WGSassign/envs/WGSassign/bin/pcangsd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Dist/anaconda-WGSassign/envs/WGSassign/lib/python3.10/site-packages/pcangsd/pcangsd.py", line 219, in main
    f = shared.emMAF(L, args.maf_iter, args.maf_tole, args.threads)
  File "/usr/local/Dist/anaconda-WGSassign/envs/WGSassign/lib/python3.10/site-packages/pcangsd/shared.py", line 50, in emMAF
    alpha = -max(1.0, sqrt(sr2/sv2))
**ZeroDivisionError: float division by zero**

 Note that I do not get this error when I run --admix on an earlier pcangsd version (1.11). We are using the same data set. Any ideas on why this would be happening with the newer version of pcangsd?

Thanks,

Christen
