### ISSUE TITLE
python pcangsd.py -h fail with ImportError: /home/ec2-user/pcangsd2/pcangsd/reader.cpython-37m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num error 

### ISSUE THREAD

**Issue by Callithrix-omics** [Rosemeis/pcangsd#27]
I am installing pcangsd on an amazon linux ec2 image. 
after running  pip dependencies command and setup.py I get the above error when trying to run pcangsd.py. 

any suggestions? 

thank you 
Joanna

**Comment by Callithrix-omics** [comment]
here is the full error message 
(env) [pcangsd]$ python pcangsd.py -h
Traceback (most recent call last):
  File "pcangsd.py", line 16, in <module>
    import reader
ImportError: /home/ec2-user/pcangsd2/pcangsd/reader.cpython-37m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num

**Comment by Rosemeis** [comment]
Hi Joanna,

It seems that something is going wrong with OpenMP (multi-threading). That means that it might be the compiler used to setup PCAngsd.

**Comment by jonaszierer** [comment]
Hi both,

I tried with gcc6.4.0 and get "undefined symbol: GOMP_barrier", which I assume is the same problem?
Any suggestions howto solve this?

thanks!
Jonas

**Comment by Rosemeis** [comment]
Hi,
Yeah, even though gcc 6.4 should have OpenMP instructions, then it seems that it is not linked properly. How are you installing it, and is it also on a Amazon Linux image?

One thing could be to make your own Anaconda environment for Python, then it should take care of all dependencies of its compiler and shared libraries.

Best,
Jonas

**Comment by jonaszierer** [comment]
puh that was a hard one. There is a bug in setup.py. for the reader module `extra_link_args=['-fopenmp'],` is missing.

**Comment by Rosemeis** [comment]
Yes that is true! Thank you catching that! :-)

/Jonas
