### ISSUE TITLE
pcangsd inbreedSites fails

### ISSUE THREAD

**Issue by jonaszierer** [Rosemeis/pcangsd#29]
I'm running pcangsd with plink files to calculate inbreedSites with `pcangsd -plink genotypes -o pcangsd -inbreed 1 -inbreedSites` for a moderatey size dataset (n~1000, ~7million variants). It outputs 

```
Parsing PLINK files
Read 1004 samples and 7065852 sites

Estimating population allele frequencies
EM (MAF) converged at iteration: 7

Killed
```

It's killed after several hours and ~180G of memory usage. Is there any way to make this more memory and time efficient? I also tried to convert to beagle first with `--post-save` but get the same result..

Thanks,
Jonas

**Comment by Rosemeis** [comment]
Hi,

Based on the output, pcangsd fails when trying to filter sites based on MAF. If it's already in PLINK format, I would do the MAF filtering in PLINK before parsing to pcangsd as it would create a copy of the genotype likelihood matrix (~ 2*3*1004*7065852*4 bytes). Then parse the PLINK files to pcangsd with '-minMaf 0.0' to avoid this.

Best,
Jonas

**Comment by jonaszierer** [comment]
thanks for the swift reply! 
It runs a bit further now but after 

```
Estimating covariance matrix
Using 4 principal components (MAP test)
|Individual allele frequencies estimated (1)
```

it fails with

```
File "./pcangsd/pcangsd.py", line 216, in <module>                                          
    C, Pi, e = covariance.pcaEM(L, args.e, f, args.iter, args.tole, args.threads)
File "./pcangsd/covariance.py", line 91, in pcaEM                                    
    diff = covariance_cy.rmse2d_eig(W, prevW)
File "covariance_cy.pyx", line 138, in covariance_cy.rmse2d_eig
    cpdef rmse2d_eig(float[:,::1] A, float[:,::1] B):
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: ndarray is not C-contiguous
```

Any idea on how to get rid of this?
More generally: Does this mean that this method will likely not work with biobank scale data (where N might be in the order of 10k or more)?

Thanks!
Jonas

**Comment by Rosemeis** [comment]
Yeah, I have seen that problem before on specific server setups and have fixed it now. You can redownload pcangsd and build setup.py again, then it should work.

We have something in the pipeline that will scale and work for biobank datasets, but only inference of population structure. The method is implemented and is called EMU under my repositories if you are interested. :-)

**Comment by jonaszierer** [comment]
cool, thanks! I will check it out. Is there a way to calculate the sHWE (i.e. per site LRT) with this as well?

**Comment by Rosemeis** [comment]
Unfortunately not yet, but it would definitely a good project for the future to implement all the features from pcangsd as 'pure' genotype methods.
