### ISSUE TITLE
pop.info file - order of samples?

### ISSUE THREAD

**Issue by TeresaPegan** [Rosemeis/pcangsd#30]
Hello,
I am using pcangsd and I have a question about creating a pop.info file like the one that is used for plotting in the tutorial http://www.popgen.dk/software/index.php/PCAngsdTutorial.
I think the order these samples are listed in determines how the points on the PCA plots are marked - if there is a mismatch between the order of samples in pop.info file, which tells the plot what population they are in, and the order of samples in the beagle file, of course the points will not be colored correctly on the PCA.

I assume that the order of the samples listed in pop.info should match the order of the bam.list I used with ANGSD to create the beagle file. If I make sure the order of pop.info matches the order of bam.list, will that ensure that my PCA results are assigned to the correct population? I just want to be sure that I'm labeling all of my data correctly since the beagle file doesn't seem to have any identifying information about any of the samples (it just calls them Ind0, Ind1, Ind2,  etc).

Thanks!
-Teresa

**Comment by Rosemeis** [comment]
Yes, exactly. The order of the individuals in the Beagle file and PCA will be the same as the bamlist. :-)

/Jonas

**Comment by TeresaPegan** [comment]
Thank you!
-Teresa
