### ISSUE TITLE
pcangsd error

### ISSUE THREAD

**Issue by biozzq** [Rosemeis/pcangsd#33]
Dear @Rosemeis ,
I ran pacngsd but giving me following error, hope you can help me.

![image](https://user-images.githubusercontent.com/15704257/82313903-98588300-99fb-11ea-9eee-5b73dba396ed.png)

Sincerely,
Zhuqing

**Comment by Rosemeis** [comment]
Dear Zhuqing,

It should have been fixed in the newest version of PCAngsd (v.0.985). :-)

Best,
Jonas
