### ISSUE TITLE
How to get the proportion of variances explained by PCs?

### ISSUE THREAD

**Issue by cteenis** [Rosemeis/pcangsd#35]
Hello,

I am using pcangsd and from the resulting covariance matrix, I can get the PCs by using eigen() function in R. Is there a way to also get the proportion of variances explained by each PC, I did not find a solution on the web.

Thanks a lot for your help!

**Comment by Rosemeis** [comment]
Hi,

After using eigen() in R, then simply use the eigenvalues. :-)
e <- eigen(C)
e$values/sum(e$values) # Proportions

Best,
Jonas

**Comment by cteenis** [comment]
@Rosemeis Thank you so much! That is very helpful (and yet so simple!)
