### ISSUE TITLE
Problem running pcangsd on mac because of zcat

### ISSUE THREAD

**Issue by elizeng** [Rosemeis/pcangsd#38]
Hi,

I ran into issues running pcangsd on my Mac, and it seems to be a zcat issue when reading the beagle file. The zcat function doesn't work as intended on the Mac, it adds an additional .Z behind the file directory specified and usually gzcat or gunzip is being used instead.

I tried looking through the python scripts to see if that could be changed, but I am however not very well versed with scripting and was unable to find the line using zcat.

Is it possible to edit the package such that it is compatible with being used on a mac as well?

Below is the script ran and the error message obtained.

Would appreciate any help rendered. Thank you!

```
Franks-Mac-Pro:shbul_round1_gatk quackquack$ python3 /Volumes/shbul/analysis/programs/pcangsd/pcangsd.py \
> -beagle /Volumes/duck2/duck2/analysis_part3/snps/duck_snpcalling/duck_round1_gatk/duck_round1.beagle.gz \
> -e 3 -o /Volumes/duck2/duck2/analysis_part3/snps/duck_snpcalling/duck_round1_gatk/pca/pcangsd_duck_round1_gatk -threads 8
PCAngsd 0.985
Using 8 thread(s)

Parsing Beagle file
zcat: can't stat: /Volumes/duck2/duck2/analysis_part3/snps/duck_snpcalling/duck_round1_gatk/duck_round1.beagle.gz (/Volumes/duck2/duck2/analysis_part3/snps/duck_snpcalling/duck_round1_gatk/duck_round1.beagle.gz.Z): No such file or directory
Read 0 samples and 0 sites

Estimating population allele frequencies
Traceback (most recent call last):
  File "/Volumes/duck/analysis/programs/pcangsd/pcangsd.py", line 204, in <module>
    f = emMaf.alleleEM(L, args.maf_iter, args.maf_tole, args.threads)
  File "/Volumes/duck/analysis/programs/pcangsd/emMaf.py", line 24, in alleleEM
    diff = shared.rmse1d(f, f_prev)
  File "shared.pyx", line 12, in shared.rmse1d
    cpdef rmse1d(float[::1] A, float[::1] B):
  File "shared.pyx", line 18, in shared.rmse1d
    res /= n
ZeroDivisionError: float division
```

**Comment by Rosemeis** [comment]
Hi,

'zcat' is being used on line 22 and 53 in 'reader.pyx', so you can change it to:
'with os.popen("gzcat " + beagle) as f:'

And then compile it again using 'python setup.py build_ext --inplace'. :-)

Best,
Jonas

**Comment by elizeng** [comment]
Hi Jonas,

Thank you for the quick reply, I tried recompiling and it seems like it may work? But I am unsure as my dataset it huge and it faced yet another error which i suspect is due to memory issues instead of coding issues.

`Killed: 9`

Would it be possible to get a test dataset to test if the edited script is functional?

Cheers

**Comment by Rosemeis** [comment]
You can download a small test dataset here:
'curl -O popgen.dk/software/download/NGSadmix/data/Demo1input.gz'

Best,
Jonas

**Comment by elizeng** [comment]
Thanks for that!
The edit works :D
