### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by dwinter** [Rosemeis/pcangsd#4]
Hello, 

First of, thanks for writing this program, which has made it very straightforward to move from GL files to a nice PCA plot. 

I am currently the methods section for an ms that has used this software, and I can't find any citation information here or at the angsd wiki. Can you let me if there is something out there that we should cite? It would also be helpful to have a GitHub "release" (or at least a tag) so we can include a URL for the specific version of the software we used.

**Comment by Rosemeis** [comment]
A pre-print for the methods on population structure is now up on biorxiv:
https://www.biorxiv.org/content/early/2018/04/17/302463
