### ISSUE TITLE
UnboundLocalError: local variable 'pr' referenced before assignment

### ISSUE THREAD

**Issue by lauraivillegasr** [Rosemeis/pcangsd#45]
Hi! I get the following error when trying to run pcangsd. I am not sure of how to solve it. 
 
 File "/home/user/pcangsd/covariance.py", line 75, in emPCA
    del d, eVal, eVec, loading, mapTest, partcov, pr
UnboundLocalError: local variable 'pr' referenced before assignment

**Comment by Rosemeis** [comment]
Hi,

Something goes wrong in the automatic selection of number of significant eigenvectors, where it doesn't seem to find anything. You can override the automatic selection with the "-e" parameter. 
Can I ask you to give a little detail about your dataset (# samples, # sites). :-)

Best,
Jonas

**Comment by lauraivillegasr** [comment]
Hi!
I have 4 samples and 4421112 sites. It has worked now using -e 3 
Thank you!
