### ISSUE TITLE
Sample projection

### ISSUE THREAD

**Issue by Wesley-sx** [Rosemeis/pcangsd#53]
Hi Jonas,

Is it possible to perform sample projection with pcangsd? 

Best,
Xin

**Comment by Rosemeis** [comment]
Hi Xin,

Sorry for the late reply. Unfortunately not at the moment but it is something that we would like to add in the future!

Best,
Jonas

**Comment by Wesley-sx** [comment]
Hi Jonas,

Thanks for your reply.

Best,
Xin
