### ISSUE TITLE
expected unicode, got str

### ISSUE THREAD

**Issue by yungsiyebu** [Rosemeis/pcangsd#57]
python2 ~/pcangsd.py -beagle ~/bam_list.beagle.gz -o ~/bam_list -threads 64

I got the error below, thank for your help

Parsing Beagle file.
Traceback (most recent call last):
  File "/home/pcangsd/pcangsd.py", line 160, in <module>
    L = reader_cy.readBeagle(args.beagle)
TypeError: Argument 'beagle' has incorrect type (expected unicode, got str)

**Comment by Rosemeis** [comment]
Hi,

This is a problem due to python2. Using python3 should fix the problem.

Best,
Jonas

**Comment by Rosemeis** [comment]
Try to make a clean install, while building using python3.

Best,
Jonas

**Comment by yungsiyebu** [comment]
Dear author,
I rebuild the env of python3.9.7 with conda, and pcangsd runs well now, Thank for your help!
best regards
wang

**Comment by Rosemeis** [comment]
That is great to hear. Thanks for reaching out!

Best,
Jonas
