### ISSUE TITLE
readgzipbeagle index error

### ISSUE THREAD

**Issue by biozzq** [Rosemeis/pcangsd#6]

**Comment by biozzq** [comment]
Dear @Rosemeis 

I found when the variants number is over 15 M, PCAngsd will give me following error. 

![image](https://user-images.githubusercontent.com/15704257/42487738-e5f29f8a-8434-11e8-8b5a-b944c0110f01.png)

Best
zhuqing

**Comment by Rosemeis** [comment]
Dear @biozzq 

Thank you so much for your observation!
I have now fixed the parsing function to handle any number of variants.

Best,
Jonas
