### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by katcatalano** [Rosemeis/pcangsd#60]
Hi! I am have a beagle.gz file output from ANGSD, and I am running into a segmentation fault error:

```
pcangsd -b angsd.beagle.gz -e 2 -t 40 -o output.pcangsd 

PCAngsd v.1.10.
Jonas Meisner and Anders Albrechtsen.
Using 40 thread(s).

Parsing Beagle file.
Loaded 5886700 sites and 159 individuals.
Estimating minor allele frequencies.
EM (MAF) converged at iteration: 57
Number of sites after MAF filtering (0.05): 5886700

Estimating covariance matrix.
Using 2 principal components (manually selected).
Segmentation fault (core dumped)
```
I don't see any formatting issues in my input file... thank you for any ideas you might have for me to troubleshoot!

**Comment by katcatalano** [comment]
Running on 1 thread solved this issue, thanks!

**Comment by agentzero93** [comment]
For future reference, I received this same error and running on 1 thread did not resolve this issue. Turns out I had a blank line on the end of my beagle file, once I removed it the issue was solved.
