### ISSUE TITLE
Cythonized pcangsd.py not working

### ISSUE THREAD

**Issue by emrullahub** [Rosemeis/pcangsd#61]
Hi, i did cythonize process with this code "python3 setup.py build_ext --inplace" but i am getting the following error when im trying to do pca with test data on pcangsd website:

PCAngsd v.1.10.
Jonas Meisner and Anders Albrechtsen.
Using 64 thread(s).

Traceback (most recent call last):
  File "pcangsd/pcangsd/pcangsd.py", line 455, in <module>
    main()
  File "pcangsd/pcangsd/pcangsd.py", line 148, in main
    from pcangsd import reader_cy
ImportError: cannot import name 'reader_cy' from 'pcangsd' (/home/emr/pcangsd/pcangsd/pcangsd.py)

Can you help me how to solve it?
Thanks,
Emrullah

![Mon 07 Mar 2022 03_08_16 PM +03](https://user-images.githubusercontent.com/62052339/158224991-325ccb2d-52b8-46af-b320-4f3350d03d33.png)

**Comment by Rosemeis** [comment]
Hi Emrullah,

The documentation on the website is a outdated in comparison to the newest PCAngsd version. So you would also need to do the following:

```
# Enter PCAngsd folder
cd pcangsd
pip3 install -e .
```

Now you should use PCAngsd by simply calling `pcangsd --beagle path/input.gz --out test` in the terminal.
Let me know if that works.

Best,
Jonas

**Comment by cnxiaobo94** [comment]
> 

hello! Dear Rosemeis, I met the same problem that "reader_cy" cannot be imported. I tried your above suggestions, but it didn't work .  Can you do me a favor? thanks
![IMG_2440](https://user-images.githubusercontent.com/67302941/181009847-de3fcaea-7442-48f7-bc3c-186da0c30cef.JPG)

**Comment by Rosemeis** [comment]
This seems to be an issue with your systems compiler versions:
https://github.com/stan-dev/pystan/issues/294

**Comment by cnxiaobo94** [comment]
> This seems to be an issue with your systems compiler versions: [stan-dev/pystan#294](https://github.com/stan-dev/pystan/issues/294)

Thank you for your quick reply. I've probably read the link you gave. Because I'm not very good at CS and bioinfor., it looks a little difficult. overall, thank you for your reply. I'll try my best to solve it, or try it on another computer.

**Comment by Rosemeis** [comment]
No problem. :-) A potential fix could be by installing the following in your conda environment:
`conda install c-compiler cxx-compiler`
And then try to remove and reinstall pcangsd. Let me know if that works.

Best,
Jonas

**Comment by cnxiaobo94** [comment]
> 

Thanks a lot!  I installed these two packages you suggested, and reinstalled pcangsd. Your suggestions worked! thanks again for solving my problem. (sorry for late reply). 

###the steps for installing pcangsd

	1.  conda install -c conda-forge c-compiler
	2.  conda install -c conda-forge cxx-compiler
	3.  git clone https://github.com/Rosemeis/pcangsd.git
	4.  cd pcangsd/
	5.  python setup.py build_ext --inplace
	6.  pip install --user -r requirements.txt
	7.  pip3 install -e .

**Comment by Rosemeis** [comment]
That is great to hear! :-)

**Comment by steigeec** [comment]
Hi! -

I have followed the workflow suggested here, removing pcangsd and re-cloning on each occasssion, as well as tried export CC=gcc prior to step 5 as recommended in issue #54 . I continue to get the error message that others have reported:

```
Traceback (most recent call last):
  File "/filepath/pcangsd/pcangsd.py", line 476, in <module>
    main()
  File "/filepath/pcangsd/pcangsd.py", line 147, in main
    from pcangsd import reader_cy
ImportError: cannot import name 'reader_cy' from 'pcangsd' (/filepath/pcangsd/pcangsd.py)
```

Do you have recommendations for the next things I might try?
Thanks so much!

**Comment by Rosemeis** [comment]
Hi @AstridAlexAndersson 

I think it might be due to two different python installations, where "pip" and "pip3" is calling different ones. Can you try reinstalling while using the first step with "pip3":
```
pip3 install --user -r requirements.txt
git clone https://github.com/Rosemeis/pcangsd.git
cd pcangsd
python setup.py build_ext --inplace
pip3 install -e .
```

Best,
Jonas

**Comment by AstridAlexAndersson** [comment]
Hi Jonas,

Thank you for your suggestion. I agree it must be some sort of version mismatch, but when I tried reinstalling with pip3 I still receive the same errors ☹

Greatly appreciate your input,
Astrid


From: Jonas Meisner ***@***.***>
Reply to: Rosemeis/pcangsd ***@***.***>
Date: Friday, 19 May 2023 at 2:43 PM
To: Rosemeis/pcangsd ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [Rosemeis/pcangsd] Cythonized pcangsd.py not working (Issue #61)


Hi @AstridAlexAndersson<https://github.com/AstridAlexAndersson>

I think it might be due to two different python installations, where "pip" and "pip3" is calling different ones. Can you try reinstalling while using the first step with "pip3":

pip3 install --user -r requirements.txt

git clone https://github.com/Rosemeis/pcangsd.git

cd pcangsd

python setup.py build_ext --inplace

pip3 install -e .

Best,
Jonas
