### ISSUE TITLE
Adding a pyproject.toml file

### ISSUE THREAD

**Issue by alxsimon** [Rosemeis/pcangsd#75]
Hi, would you consider adding a pyproject.toml file in the project, like in this fork? https://github.com/alxsimon/pcangsd/blob/master/pyproject.toml
This would simplify having pcangsd as a dependency greatly.

You can also add the package metadata in there
https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata

Thanks!
Alexis

**Comment by Rosemeis** [comment]
Hey Alexis,

Yes I will soon do a small update to pcangsd, where I will include a pyproject.toml to make installation etc. much easier!
Thanks for asking and bringing it up.

Best,
Jonas

**Comment by Rosemeis** [comment]
I have now completed a major update to pcangsd (v1.2) including a "pyproject.toml". :-)
Sorry that it took so long time.

Best,
Jonas

**Comment by alxsimon** [comment]
Thanks!
