### ISSUE TITLE
latest version (1.10) has not been tagged 

### ISSUE THREAD

**Issue by jowodo** [Rosemeis/pcangsd#78]
Old commits can easily be tagged. See [this stackoverflow answer](https://stackoverflow.com/a/18223354). 
Please tag at least the latest version. 

Thanks :)

**Comment by jowodo** [comment]
I also noticed, that tag version 0.937 does not have the 'v' in front of it as the other tags do. 
See [this stackoverflow answer](https://stackoverflow.com/a/5719854) on how to rename a tag. 

Thanks for you time

**Comment by Rosemeis** [comment]
Thanks, I have tried to fix the mess a bit. New major update v1.2 including release.

**Comment by jowodo** [comment]
Hi, 

I just noticed, that the newest version will not be recognized by the `--version-sort` option of `sort` as the latest version: 
```
git ls-remote --tags https://github.com/Rosemeis/pcangsd | cut -f2 | sed 's/^refs.//' | sed 's/^tags.//' | sed 's/^v//' | grep '^[0-9]' | sort --version-sort
```
I'll use `sort` without the --version-sort option for now. 

Maybe version 1.10 can be rename to 1.1.0?
