### ISSUE TITLE
Empty string "" in various outputs

### ISSUE THREAD

**Issue by kdmurray91** [Rosemeis/pcangsd#8]
Hi Jonas,

Thanks for PCAngsd! We're finding it extremely useful.

One small quirk we've come across is that Pandas seems to output some values as `""`. I assume these are NaNs, is that correct? I've seen this in the inbreeding file. If these `""`s do represent NaN, is there a way of convincing Pandas to output them as "NaN" or some other marker that's recognised as NaN?

Thanks again,
Kevin

**Comment by Rosemeis** [comment]
Hi Kevin,

Thank you! I'm very glad to hear this.

Yes, that does seem to be the problem for Pandas. I have now uploaded an entire rewrite of the inbreeding estimations such that the estimation is much more stablized and NaNs should never occur now. And the per-individual inbreeding estimations are now multithreaded as well.

I'm assuming that the NaN was produced using -inbreed 2?

And thank you for pointing out the bug for -allocate_sites as well, which is also now taken into account!

Best,
Jonas

**Comment by kdmurray91** [comment]
Thanks Jonas!

You're correct, the NaNs were with `-inbreed 2`.

Cheers,
Kevin
