### ISSUE TITLE
How is the K chosen in the program?

### ISSUE THREAD

**Issue by yksakana** [Rosemeis/pcangsd#82]
Hi,
I apologize for the multiple posts.
I am currently working on admixture analysis using pcangsd utilizing the following command:
`pcangsd -b genolike.beagle.gz --iter 2000 -e 10 -o pcangsd_out --admix`

I've encountered a bit of confusion about the choice of the number K in the program and its connection to the parameter -e, which represents the number of eigenvalues.

Specifically, when I set -e to 10, the program sets K=11. Conversely, when -e is set to 1, the program sets K=2. Does this imply that K is set to e+1?

Additionally, I'm keen to compare the Frobenius error when K is 1 and 2. Even if I set -e to 0, the program defaults to K=2, preventing me from obtaining the error for K=1. I am aware of the option to manually select K using -admix_K, but as it's not recommended [(please see here),](http://www.popgen.dk/software/index.php/PCAngsd) I'm unsure how to obtain the Frobenius error when K=1.

Should I proceed by specifying the value of K using the -admix_K option, or are there alternative methods to obtain the Frobenius error for K=1?

Thank you for your assistance.

**Comment by Rosemeis** [comment]
Hi,

Yes it is directly implied that K = e + 1, as if you have K distinct populations, then you would only need e = K - 1 eigenvectors to model them. (https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.0020190)

I'm not sure I understand the last question. It seems you want to estimate admixture proportions when only assuming 1 ancestral population?

Best,
Jonas

**Comment by yksakana** [comment]
Hi,

Thank you very much for your reply, and sorry for my late reply.
I understood that K would be equal to e+1, thank you very much.

In the last question, Yes. I'd like to know which better explains my data, assuming 1 cluster or 2 clusters.
For example, in the ADMIXTURE software, we can judge which would be better by comparing cross-validation errors.
How can I do it in pcangsd?

Best,
Yusuke
